import type { Issue } from '../types.js';

/**
 * DKIM conditions. RFC 6376 (DKIM), RFC 8301 (crypto requirements),
 * RFC 8463 (Ed25519).
 *
 * DKIM has no discoverable index: a domain's selectors are only knowable from a
 * signed message. We probe the selectors real providers actually use, and when
 * none answer we say so plainly rather than declaring DKIM missing.
 */
export const DKIM_ISSUES: readonly Issue[] = [
  {
    code: 'DKIM_SELECTOR_NOT_FOUND',
    record: 'DKIM',
    severity: 'INFO',
    category: 'existence',
    title: 'No DKIM key found at the usual selectors',
    why: 'We probed {count} selectors that Google, Microsoft, Zoho, Mailchimp and the other common providers use, and none of them answered for {domain}. That means either nothing signs your mail, or it signs with a selector only you know.',
    fix: 'Look at the DKIM-Signature header of a message you sent, the s= value is your selector, and check it directly. If there is no such header, enable DKIM signing in your mail provider.',
    rfc: 'RFC 6376 section 3.6.2.1',
    dismissible: true,
    vars: ['domain', 'count'],
  },
  {
    code: 'DKIM_RECORD_MISSING',
    record: 'DKIM',
    severity: 'HIGH',
    category: 'existence',
    title: 'No DKIM key at the selector you gave',
    why: 'Nothing is published at {selector}._domainkey.{domain}. Mail signed with that selector cannot be verified, which costs you deliverability and removes one of the two ways DMARC can pass.',
    fix: 'Publish the public key your provider gave you at {selector}._domainkey.{domain}, or correct the selector name.',
    rfc: 'RFC 6376 section 3.6.2.1',
    vars: ['selector', 'domain'],
  },
  {
    code: 'DKIM_KEY_REVOKED',
    record: 'DKIM',
    severity: 'CRITICAL',
    category: 'crypto',
    title: 'DKIM key at {selector} has been revoked',
    why: 'The record at {selector}._domainkey.{domain} has an empty p= value, which formally revokes the key. Every signature made with it fails, so signed mail is treated as unsigned.',
    fix: 'Publish the current public key in the p= tag, or remove the record entirely if the selector is retired.',
    rfc: 'RFC 6376 section 3.6.1',
    vars: ['selector', 'domain'],
  },
  {
    code: 'DKIM_RECORD_BROKEN',
    record: 'DKIM',
    severity: 'CRITICAL',
    category: 'syntax',
    title: 'DKIM record at {selector} cannot be read',
    why: 'The record at {selector}._domainkey.{domain} has no usable public key, either the p= tag is absent or the key data does not decode. Verifiers reject every signature that points here.',
    fix: 'Republish the key exactly as your provider issued it, on one line, with no spaces inserted by the DNS panel.',
    rfc: 'RFC 6376 section 3.6.1',
    vars: ['selector', 'domain'],
  },
  {
    code: 'DKIM_KEY_TOO_WEAK',
    record: 'DKIM',
    severity: 'CRITICAL',
    category: 'crypto',
    title: 'DKIM key at {selector} is below the minimum size',
    why: 'The key at {selector} is {bits} bits. Verifiers must not accept RSA keys under 1024 bits, so your signatures are treated as invalid, signing this mail achieves nothing at all.',
    fix: 'Generate a new 2048-bit key in your mail provider and publish it, then remove the old selector once the change has propagated.',
    rfc: 'RFC 8301 section 3.2',
    vars: ['selector', 'bits'],
  },
  {
    code: 'DKIM_KEY_WEAK_1024',
    record: 'DKIM',
    severity: 'MEDIUM',
    category: 'crypto',
    title: 'DKIM key at {selector} is only 1024 bits',
    why: 'The key at {selector} is the bare minimum receivers will accept. It works today, and the standard asks for 2048, the gap between "accepted" and "trusted" is where deliverability quietly lives.',
    fix: 'Rotate to a 2048-bit key when convenient. Most providers do it in one click and keep the old selector alive during the change.',
    rfc: 'RFC 8301 section 3.2',
    vars: ['selector'],
  },
  {
    code: 'DKIM_ALGO_UNKNOWN',
    record: 'DKIM',
    severity: 'HIGH',
    category: 'crypto',
    title: 'DKIM key at {selector} uses an unrecognised algorithm',
    why: 'k={offending_term} at {selector} is not an algorithm verifiers implement. The key is ignored and the signature fails.',
    fix: 'Publish the key as k=rsa, or k=ed25519 if your provider supports it.',
    rfc: 'RFC 6376 section 3.6.1',
    vars: ['selector', 'offending_term'],
  },
  {
    code: 'DKIM_ALGO_SHA1',
    record: 'DKIM',
    severity: 'HIGH',
    category: 'crypto',
    title: 'DKIM key at {selector} is restricted to SHA-1',
    why: 'The record at {selector} permits only rsa-sha1, which must no longer be used. Signatures made with it have permanently failed evaluation, so this key protects nothing.',
    fix: 'Remove the h=sha1 restriction so SHA-256 is used, and rotate the key if your provider still signs with SHA-1.',
    rfc: 'RFC 8301 section 3.1',
    vars: ['selector'],
  },
  {
    code: 'DKIM_ED25519_INVALID',
    record: 'DKIM',
    severity: 'HIGH',
    category: 'crypto',
    title: 'Ed25519 DKIM key at {selector} is malformed',
    why: 'An Ed25519 public key is exactly 32 bytes; the key at {selector} decodes to {bits} bits. Verifiers cannot use it, so signatures fail.',
    fix: 'Republish the Ed25519 key exactly as issued, it is a short base64 string and is easily truncated when pasted.',
    rfc: 'RFC 8463 section 3',
    vars: ['selector', 'bits'],
  },
  {
    code: 'DKIM_TESTING_MODE',
    record: 'DKIM',
    severity: 'LOW',
    category: 'policy',
    title: 'DKIM selector {selector} is in testing mode',
    why: 't=y at {selector} tells receivers to treat signatures as experimental, so a failed signature carries no consequence. It is meant for the week you roll DKIM out, not for permanent use.',
    fix: 'Remove t=y from the record once you have confirmed your mail verifies.',
    rfc: 'RFC 6376 section 3.6.1',
    vars: ['selector'],
  },
  {
    code: 'DKIM_DUPLICATE_TAG',
    record: 'DKIM',
    severity: 'HIGH',
    category: 'syntax',
    title: 'DKIM record at {selector} repeats a tag',
    why: 'The tag {offending_term} appears more than once at {selector}, which makes the record invalid. Verifiers are entitled to discard it entirely.',
    fix: 'Keep one instance of {offending_term} and remove the duplicate.',
    rfc: 'RFC 6376 section 3.2',
    vars: ['selector', 'offending_term'],
  },
  {
    code: 'DKIM_MULTIPLE_RECORDS',
    record: 'DKIM',
    severity: 'HIGH',
    category: 'existence',
    title: 'Multiple DKIM records at {selector}',
    why: '{count} TXT records answer at {selector}._domainkey.{domain}. Verifiers cannot tell which key is yours and may pick the wrong one, so verification becomes a coin toss.',
    fix: 'Keep exactly one TXT record at that selector and delete the rest. It is usually a leftover from a provider migration.',
    rfc: 'RFC 6376 section 3.6.2.2',
    vars: ['selector', 'domain', 'count'],
  },
  {
    code: 'DKIM_SERVICE_RESTRICTED',
    record: 'DKIM',
    severity: 'LOW',
    category: 'policy',
    title: 'DKIM key at {selector} is restricted to specific services',
    why: 'The s= tag at {selector} limits this key to {offending_term}. If it does not include email, ordinary mail signed with this key will not verify.',
    fix: 'Set s=* (the default) unless you have a specific reason to restrict the key.',
    rfc: 'RFC 6376 section 3.6.1',
    dismissible: true,
    vars: ['selector', 'offending_term'],
  },
  {
    code: 'DKIM_WILDCARD_REVOKED',
    record: 'DKIM',
    severity: 'INFO',
    category: 'crypto',
    title: 'A wildcard answers every DKIM selector, with the key revoked',
    why: 'Every selector we asked about on {domain} returned the same record with an empty p= tag, including one we invented. That is a wildcard publishing a revoked key, and it is the standard way to say this domain signs no mail at all. We checked {count} selectors and they are one record, not {count} problems.',
    fix: 'Nothing, if the domain is not meant to send mail. If it is, publish a real key at a named selector, because a wildcard revocation tells every receiver to distrust any signature claiming to come from here.',
    rfc: 'RFC 6376 section 3.6.1',
    vars: ['domain', 'count'],
    dismissible: true,
  },
  {
    code: 'DKIM_WILDCARD_KEY',
    record: 'DKIM',
    severity: 'HIGH',
    category: 'crypto',
    title: 'A wildcard publishes the same DKIM key at every selector',
    why: 'Every selector we asked about on {domain} returned the same key, including one we invented. Anyone who can sign with that key can pick any selector name they like and it will verify, so rotating a compromised selector does nothing and you cannot retire a key without retiring all of them.',
    fix: 'Remove the wildcard TXT record under _domainkey and publish each key at its own named selector. Wildcards under _domainkey exist almost always by accident, usually a *.{domain} record meant for something else.',
    rfc: 'RFC 6376 section 3.6.1',
    vars: ['domain'],
  },
];
