import type { Issue } from '../types.js';

/**
 * DMARC conditions. RFC 9989 (DMARC), RFC 9990 (aggregate reporting),
 * RFC 9991 (failure reporting).
 *
 * RFC 9989 obsoletes RFC 7489 *and* RFC 9091, and three of its changes matter
 * enough to call out, because most tools (and most blog posts) still have them
 * wrong:
 *
 *   - Only `v` is required (§4.8). A syntactically valid record with no `p` is
 *     treated as `p=none`. it is NOT discarded.
 *   - `psd` takes `y`, `n` or `u`, defaulting to `u` (§4.7.6).
 *   - Policy discovery is the DNS tree walk (§4.10), not the Public Suffix List.
 */
export const DMARC_ISSUES: readonly Issue[] = [
  // --- Discovery & existence ------------------------------------------------
  {
    code: 'DMARC_RECORD_MISSING',
    record: 'DMARC',
    severity: 'CRITICAL',
    category: 'existence',
    title: 'No DMARC record',
    why: 'Nothing at _dmarc.{domain} tells receivers what to do with mail that fails authentication, so anyone can send phishing that looks exactly like you, and you never find out, because there are no reports either.',
    fix: 'Publish a TXT record at _dmarc.{domain}: v=DMARC1; p=none; rua=mailto:dmarc@{domain}, start at none to collect reports, then move to quarantine and reject.',
    rfc: 'RFC 9989 §4.5',
    vars: ['domain'],
  },
  {
    code: 'DMARC_MULTIPLE_RECORDS',
    record: 'DMARC',
    severity: 'CRITICAL',
    category: 'existence',
    title: 'Multiple DMARC records',
    why: '{count} DMARC records are published at _dmarc.{domain}. Receivers require exactly one. Finding several. They apply no policy at all, so you have the appearance of DMARC and none of the protection.',
    fix: 'Delete every DMARC record but the one you want enforced. There must be exactly one TXT record at _dmarc.{domain}.',
    rfc: 'RFC 9989 §4.10',
    vars: ['domain', 'count'],
  },
  {
    code: 'DMARC_EMPTY_RECORD',
    record: 'DMARC',
    severity: 'CRITICAL',
    category: 'existence',
    title: 'DMARC record contains no policy',
    why: 'The record at _dmarc.{domain} is just a version tag with nothing after it. It parses, and it does nothing.',
    fix: 'Add a policy and a reporting address: v=DMARC1; p=none; rua=mailto:dmarc@{domain}',
    rfc: 'RFC 9989 §4.8',
    vars: ['domain'],
  },
  {
    code: 'DMARC_TREE_WALK_CAPPED',
    record: 'DMARC',
    severity: 'CRITICAL',
    category: 'existence',
    title: 'DMARC policy discovery ran out of queries',
    why: 'Receivers walk up the DNS tree looking for your policy and stop after 8 queries. {domain} is deep enough that the walk ends before a record is found, so receivers apply no DMARC at all.',
    fix: 'Publish a DMARC record closer to the sending domain, at {domain} itself, or at its organizational domain.',
    rfc: 'RFC 9989 §4.10',
    vars: ['domain'],
  },
  {
    code: 'DMARC_POLICY_INHERITED',
    record: 'DMARC',
    severity: 'HIGH',
    category: 'existence',
    title: 'DMARC policy is inherited from a parent domain',
    why: '{domain} publishes no DMARC record of its own. Receivers are applying the policy found at {source_domain}, which someone else controls and can change or remove without telling you.',
    fix: 'Publish your own record at _dmarc.{domain} with your own reporting addresses, so you control the policy and can see your own mail.',
    rfc: 'RFC 9989 §4.10.1',
    vars: ['domain', 'source_domain'],
  },
  {
    code: 'DMARC_CNAME_LOOP',
    record: 'DMARC',
    severity: 'CRITICAL',
    category: 'existence',
    title: 'DMARC record is behind a CNAME loop',
    why: 'The CNAME chain at _dmarc.{domain} comes back on itself ({chain_path}), so resolution never terminates and no policy is ever found.',
    fix: 'Remove the circular CNAME and point _dmarc.{domain} at a name that resolves to a real TXT record.',
    rfc: 'RFC 9989 §4.5',
    vars: ['domain', 'chain_path'],
  },
  {
    code: 'DMARC_CNAME_BROKEN',
    record: 'DMARC',
    severity: 'CRITICAL',
    category: 'existence',
    title: 'DMARC CNAME points nowhere',
    why: '_dmarc.{domain} is a CNAME to {target}, and nothing resolves there. This is the real reason your DMARC looks missing, the delegation is broken, not the policy.',
    fix: 'Fix or remove the CNAME so _dmarc.{domain} reaches a valid DMARC TXT record.',
    rfc: 'RFC 9989 §4.5',
    vars: ['domain', 'target'],
  },

  // --- Version & syntax (a bad `v` makes receivers ignore everything) --------
  {
    code: 'DMARC_V_CASE_INVALID',
    record: 'DMARC',
    severity: 'CRITICAL',
    category: 'syntax',
    title: 'DMARC version tag is wrong',
    why: 'The version must be exactly v=DMARC1, case included. Anything else and receivers ignore the entire record, every other tag you have set is irrelevant.',
    fix: 'Set the first tag to exactly v=DMARC1 (uppercase DMARC, digit one).',
    rfc: 'RFC 9989 §4.8',
    vars: [],
  },
  {
    code: 'DMARC_V_OUT_OF_ORDER',
    record: 'DMARC',
    severity: 'CRITICAL',
    category: 'syntax',
    title: 'DMARC version tag is not first',
    why: 'v=DMARC1 must be the first tag in the record. When it is not, receivers ignore the whole record, including your policy.',
    fix: 'Move v=DMARC1 to the very start: v=DMARC1; p=…; rua=…',
    rfc: 'RFC 9989 §4.8',
    vars: [],
  },
  {
    code: 'DMARC_DUPLICATE_TAG',
    record: 'DMARC',
    severity: 'CRITICAL',
    category: 'syntax',
    title: 'DMARC record repeats a tag',
    why: 'The tag {offending_term} appears more than once. Which value applies is undefined, and strict receivers treat the record as unparseable.',
    fix: 'Keep one instance of {offending_term} and delete the rest.',
    rfc: 'RFC 9989 §4.8',
    vars: ['offending_term'],
  },
  {
    code: 'DMARC_SYNTAX_DELIMITER',
    record: 'DMARC',
    severity: 'CRITICAL',
    category: 'syntax',
    title: 'DMARC tags are not separated correctly',
    why: 'Part of the record ({offending_term}) is not a tag=value pair separated by a semicolon, so parsing stops or produces something you did not intend.',
    fix: 'Separate every tag with a semicolon: v=DMARC1; p=reject; rua=mailto:dmarc@example.com',
    rfc: 'RFC 9989 §4.8',
    vars: ['offending_term'],
  },
  {
    code: 'DMARC_UNPARSEABLE',
    record: 'DMARC',
    severity: 'CRITICAL',
    category: 'syntax',
    title: 'DMARC record cannot be parsed',
    why: 'The record at _dmarc.{domain} does not decompose into tag=value pairs at all, so it provides no protection whatsoever.',
    fix: 'Replace it with a clean record: v=DMARC1; p=none; rua=mailto:dmarc@{domain}',
    rfc: 'RFC 9989 §4.8',
    vars: ['domain'],
  },
  {
    code: 'DMARC_UPPERCASE_TAGS',
    record: 'DMARC',
    severity: 'LOW',
    category: 'syntax',
    title: 'DMARC tag names use uppercase',
    why: 'Tag names ({offending_term}) should be lowercase. Most receivers cope, but some do not, and it is a needless risk on a record this important.',
    fix: 'Write tag names in lowercase: p, sp, rua, adkim.',
    rfc: 'RFC 9989 §4.8',
    vars: ['offending_term'],
  },
  {
    code: 'DMARC_STRING_TOO_LONG',
    record: 'DMARC',
    severity: 'LOW',
    category: 'transport',
    title: 'DMARC record exceeds a single DNS string',
    why: 'The record is {count} bytes, so it must be published as several quoted strings, and DNS panels that get that wrong silently mangle it.',
    fix: 'Shorten the record, usually by reducing reporting addresses, or publish it as multiple quoted strings in one TXT record.',
    rfc: 'RFC 9989 §4.8',
    vars: ['count'],
  },
  {
    code: 'DMARC_UDP_TRUNCATION',
    record: 'DMARC',
    severity: 'LOW',
    category: 'transport',
    title: 'DMARC record is large enough to be truncated',
    why: 'At {count} bytes the DNS response risks truncation on resolvers without EDNS0, and a truncated policy is an unread policy.',
    fix: 'Trim the record, the usual cause is a long list of reporting destinations.',
    rfc: 'RFC 9989 §4.8',
    vars: ['count'],
  },

  // --- Core policy ----------------------------------------------------------
  {
    code: 'DMARC_P_MISSING',
    record: 'DMARC',
    severity: 'HIGH',
    category: 'policy',
    title: 'DMARC record has no policy tag',
    why: 'With no p tag, receivers treat the record as p=none, monitoring only. The record is valid, which is exactly why this goes unnoticed: it looks like protection and blocks nothing.',
    fix: 'State the policy explicitly. Add p=none while you review reports, then move to p=quarantine and p=reject.',
    rfc: 'RFC 9989 §4.7.5',
    vars: [],
  },
  {
    code: 'DMARC_P_INVALID',
    record: 'DMARC',
    severity: 'CRITICAL',
    category: 'policy',
    title: 'DMARC policy value is invalid',
    why: 'p={offending_term} is not a policy any receiver recognises. The intended enforcement never happens.',
    fix: 'Use exactly one of p=none, p=quarantine or p=reject.',
    rfc: 'RFC 9989 §4.7.5',
    vars: ['offending_term'],
  },
  {
    code: 'DMARC_P_NONE',
    record: 'DMARC',
    severity: 'HIGH',
    category: 'policy',
    title: 'DMARC is monitoring only (p=none)',
    why: 'p=none tells receivers to deliver mail that fails authentication anyway. You can see spoofing in the reports, but nothing is stopped, {domain} is still fully spoofable today.',
    fix: 'Review your aggregate reports until only known senders pass, then move to p=quarantine, and finally p=reject.',
    rfc: 'RFC 9989 §4.7.5',
    vars: ['domain'],
  },
  {
    code: 'DMARC_P_QUARANTINE',
    record: 'DMARC',
    // Quarantine is most of the way there: forged mail is caught, it just
    // lands somewhere a determined recipient can still reach. Weighting it
    // like a genuine gap put well-run domains next to domains with nothing.
    severity: 'LOW',
    category: 'policy',
    title: 'DMARC quarantines instead of rejecting',
    why: 'Mail that fails authentication for {domain} is delivered to spam rather than refused. Better than nothing, and one step short of protection, a spoofed message still reaches the mailbox.',
    fix: 'Once your reports show only legitimate senders passing, change p=quarantine to p=reject.',
    rfc: 'RFC 9989 §4.7.5',
    vars: ['domain'],
  },
  {
    code: 'DMARC_SP_INVALID',
    record: 'DMARC',
    severity: 'MEDIUM',
    category: 'policy',
    title: 'Subdomain policy value is invalid',
    why: 'sp={offending_term} is not a valid policy, so receivers fall back to your main policy for subdomains, which may be stricter or weaker than you intended.',
    fix: 'Use sp=none, sp=quarantine or sp=reject, or remove the tag to inherit p.',
    rfc: 'RFC 9989 §4.7.9',
    vars: ['offending_term'],
  },
  {
    code: 'DMARC_NP_INVALID',
    record: 'DMARC',
    severity: 'MEDIUM',
    category: 'policy',
    title: 'Non-existent subdomain policy value is invalid',
    why: 'np={offending_term} is not a valid policy, so receivers fall back to sp or p for subdomains that do not exist.',
    fix: 'Use np=none, np=quarantine or np=reject, or remove the tag.',
    rfc: 'RFC 9989 §4.7.4',
    vars: ['offending_term'],
  },
  {
    code: 'DMARC_WEAKER_SP',
    record: 'DMARC',
    severity: 'HIGH',
    category: 'policy',
    title: 'Subdomains are less protected than the domain',
    why: 'The domain enforces p={policy} but subdomains only get sp={subdomain_policy}. Attackers know this: they spoof invoices.{domain} precisely because the subdomain policy is the weak one.',
    fix: 'Raise sp to match your domain policy, sp={policy}, unless you have a specific subdomain that genuinely needs the weaker setting.',
    rfc: 'RFC 9989 §4.7.9',
    vars: ['domain', 'policy', 'subdomain_policy'],
  },
  {
    code: 'DMARC_WEAKER_NP',
    record: 'DMARC',
    severity: 'HIGH',
    category: 'policy',
    title: 'Non-existent subdomains are less protected',
    why: 'Mail claiming to come from subdomains that do not exist is handled with np={np_policy}, weaker than the sp={subdomain_policy} you apply elsewhere. Invented subdomains are the easiest thing in the world to spoof.',
    fix: 'Set np=reject. No legitimate mail comes from a subdomain that does not exist.',
    rfc: 'RFC 9989 §4.7.4',
    vars: ['np_policy', 'subdomain_policy'],
  },

  // --- Test mode & alignment -----------------------------------------------
  {
    code: 'DMARC_STALE_TEST_MODE',
    record: 'DMARC',
    severity: 'CRITICAL',
    category: 'policy',
    title: 'DMARC is in test mode while claiming to enforce',
    why: 't=y tells receivers to apply p=none no matter what your policy says. Your record advertises p={policy} and delivers nothing of the sort, this is the single most common way a domain believes it is protected and is not.',
    fix: 'Remove t=y once your rollout is validated. The policy takes effect the moment you do.',
    rfc: 'RFC 9989 §4.7.10',
    vars: ['policy'],
  },
  {
    code: 'DMARC_T_INVALID',
    record: 'DMARC',
    severity: 'MEDIUM',
    category: 'policy',
    title: 'Test mode value is invalid',
    why: 't={offending_term} is not valid, so receivers fall back to t=n. If you meant to be in test mode, you are not.',
    fix: 'Use t=y for test mode or t=n (the default) for normal enforcement.',
    rfc: 'RFC 9989 §4.7.10',
    vars: ['offending_term'],
  },
  {
    code: 'DMARC_ADKIM_INVALID',
    record: 'DMARC',
    severity: 'MEDIUM',
    category: 'alignment',
    title: 'DKIM alignment value is invalid',
    why: 'adkim={offending_term} is not valid, so receivers use relaxed alignment. If you intended strict, you are not getting it.',
    fix: 'Use adkim=r for relaxed or adkim=s for strict.',
    rfc: 'RFC 9989 §4.7.1',
    vars: ['offending_term'],
  },
  {
    code: 'DMARC_ASPF_INVALID',
    record: 'DMARC',
    severity: 'MEDIUM',
    category: 'alignment',
    title: 'SPF alignment value is invalid',
    why: 'aspf={offending_term} is not valid, so receivers use relaxed alignment. If you intended strict, you are not getting it.',
    fix: 'Use aspf=r for relaxed or aspf=s for strict.',
    rfc: 'RFC 9989 §4.7.2',
    vars: ['offending_term'],
  },
  {
    code: 'DMARC_ADKIM_STRICT_ADV',
    record: 'DMARC',
    severity: 'INFO',
    category: 'alignment',
    title: 'Strict DKIM alignment is on',
    why: 'adkim=s requires the DKIM signing domain to match your From domain exactly. Any vendor signing with their own domain, and any subdomain sender, will fail DMARC.',
    fix: 'Confirm every sender signs as {domain} exactly, or switch to adkim=r.',
    rfc: 'RFC 9989 §4.7.1',
    dismissible: true,
    vars: ['domain'],
  },
  {
    code: 'DMARC_ASPF_STRICT_ADV',
    record: 'DMARC',
    severity: 'INFO',
    category: 'alignment',
    title: 'Strict SPF alignment is on',
    why: 'aspf=s requires the SPF-authenticated domain to match your From domain exactly. Subdomain senders and some forwarding paths will fail DMARC as a result.',
    fix: 'Confirm every sender uses {domain} exactly in the envelope sender, or switch to aspf=r.',
    rfc: 'RFC 9989 §4.7.2',
    dismissible: true,
    vars: ['domain'],
  },
  {
    code: 'DMARC_PSD_INVALID',
    record: 'DMARC',
    severity: 'MEDIUM',
    category: 'policy',
    title: 'Public suffix flag value is invalid',
    why: 'psd={offending_term} is not valid. The tag takes y, n or u, and an invalid value falls back to u, leaving receivers to work out for themselves whether this is an organizational domain.',
    fix: 'Use psd=n if this is a normal domain, psd=y only if you operate a public suffix, or remove the tag entirely.',
    rfc: 'RFC 9989 §4.7.6',
    vars: ['offending_term'],
  },
  {
    code: 'DMARC_ORG_DOMAIN_IS_PSD',
    record: 'DMARC',
    severity: 'CRITICAL',
    category: 'policy',
    title: 'A normal domain is claiming to be a public suffix',
    why: 'psd=y declares {domain} a registry under which other people register names. On an ordinary domain it distorts policy discovery for you and potentially for others.',
    fix: 'Remove psd=y, or set psd=n to state plainly that {domain} is an organizational domain.',
    rfc: 'RFC 9989 §4.7.6',
    vars: ['domain'],
  },
  {
    code: 'DMARC_OBSOLETE_TAGS',
    record: 'DMARC',
    severity: 'LOW',
    category: 'policy',
    title: 'DMARC record uses retired tags',
    why: 'The tags {offending_term} were removed in the current DMARC standard. Receivers ignore them, so any rollout you think they are controlling is not happening.',
    fix: 'Delete {offending_term}. Use t=y for a staged rollout instead of pct.',
    rfc: 'RFC 9989 Appendix A.6',
    vars: ['offending_term'],
  },

  // --- Reporting ------------------------------------------------------------
  {
    code: 'DMARC_RUA_MISSING',
    record: 'DMARC',
    severity: 'HIGH',
    category: 'reporting',
    title: 'DMARC has no reporting address',
    why: 'Without rua, no receiver sends you aggregate reports. You cannot see who is sending as {domain}, cannot tell legitimate senders from spoofers, and cannot safely tighten your policy.',
    fix: 'Add a reporting destination: rua=mailto:dmarc@{domain}. Reports start arriving within a day.',
    rfc: 'RFC 9989 §4.7.7',
    vars: ['domain'],
  },
  {
    code: 'DMARC_BLIND_REJECT',
    record: 'DMARC',
    severity: 'CRITICAL',
    category: 'reporting',
    title: 'Enforcing DMARC with no visibility',
    why: '{domain} is at p={policy} with no rua address. Receivers are refusing or quarantining mail on your behalf and you have no way to see whose mail it was, including your own.',
    fix: 'Add rua=mailto:dmarc@{domain} today. If legitimate mail is being blocked, the reports are the only place that shows it.',
    rfc: 'RFC 9990 §3',
    vars: ['domain', 'policy'],
  },
  {
    code: 'DMARC_RUA_NO_MAILTO',
    record: 'DMARC',
    severity: 'CRITICAL',
    category: 'reporting',
    title: 'Reporting destination is missing mailto:',
    why: '{offending_term} is not a usable reporting URI. Receivers discard destinations they cannot parse, so those reports are simply never sent.',
    fix: 'Prefix every destination with mailto:, e.g. Rua=mailto:dmarc@{domain}',
    rfc: 'RFC 9989 §4.6',
    vars: ['offending_term', 'domain'],
  },
  {
    code: 'DMARC_RUA_MALFORMED',
    record: 'DMARC',
    severity: 'HIGH',
    category: 'reporting',
    title: 'Reporting address is not a valid email address',
    why: '{offending_term} cannot receive mail as written, so those reports are dropped silently. You would never know the difference between this and nobody spoofing you.',
    fix: 'Correct the address in the rua tag to a mailbox that exists and is monitored.',
    rfc: 'RFC 9989 §4.6',
    vars: ['offending_term'],
  },
  {
    code: 'DMARC_URI_UNENCODED',
    record: 'DMARC',
    severity: 'HIGH',
    category: 'reporting',
    title: 'Reporting URI contains unencoded characters',
    why: 'The commas or exclamation marks inside {offending_term} are structural in a DMARC record. Unencoded. They split the URI into fragments and the reports go nowhere.',
    fix: 'Percent-encode reserved characters inside the address: , becomes %2C and ! becomes %21.',
    rfc: 'RFC 9989 §4.6',
    vars: ['offending_term'],
  },
  {
    code: 'DMARC_RUA_SIZE_INVALID',
    record: 'DMARC',
    severity: 'LOW',
    category: 'reporting',
    title: 'Report size limit is malformed',
    why: 'The size modifier {offending_term} is not valid, so receivers may ignore the whole destination rather than just the limit.',
    fix: 'Write the limit as a number with an optional unit, e.g. Mailto:dmarc@example.com!10m, or drop it entirely.',
    rfc: 'RFC 9989 §4.6',
    vars: ['offending_term'],
  },
  {
    code: 'DMARC_RUA_BAD_DELIMITER',
    record: 'DMARC',
    severity: 'MEDIUM',
    category: 'reporting',
    title: 'Reporting destinations separated by spaces',
    why: 'Multiple destinations must be comma-separated. Written with spaces, everything after the first address is misread and those reports never arrive.',
    fix: 'Separate destinations with commas only: rua=mailto:a@example.com,mailto:b@example.com',
    rfc: 'RFC 9989 §4.6',
    vars: [],
  },
  {
    code: 'DMARC_TOO_MANY_URIS',
    record: 'DMARC',
    severity: 'LOW',
    category: 'reporting',
    title: 'Too many reporting destinations',
    why: '{count} destinations are configured. Receivers are permitted to send to fewer than you list, so past a small number the receiver decides which of your addresses actually get a copy.',
    fix: 'Keep two or three destinations and forward from there if more people need the data.',
    rfc: 'RFC 9989 §4.6',
    vars: ['count'],
  },
  {
    code: 'DMARC_FO_INVALID',
    record: 'DMARC',
    severity: 'LOW',
    category: 'reporting',
    title: 'Failure reporting options are invalid',
    why: 'fo={offending_term} is not valid, so receivers fall back to fo=0, failure reports only when everything fails, which is rarely what people intend.',
    fix: 'Use fo=1 to get a report whenever any check fails, or combine values with colons, e.g. fo=d:s',
    rfc: 'RFC 9989 §4.7.3',
    vars: ['offending_term'],
  },
  {
    code: 'DMARC_RUF_NO_MAILTO',
    record: 'DMARC',
    severity: 'MEDIUM',
    category: 'reporting',
    title: 'Failure report destination is missing mailto:',
    why: '{offending_term} is not a usable URI, so failure reports for {domain} are discarded before they are sent.',
    fix: 'Prefix the destination with mailto:, or remove the ruf tag if you do not want per-message reports.',
    rfc: 'RFC 9991 §2',
    vars: ['offending_term', 'domain'],
  },
  {
    code: 'DMARC_RUF_MALFORMED',
    record: 'DMARC',
    severity: 'MEDIUM',
    category: 'reporting',
    title: 'Failure report address is not a valid email address',
    why: '{offending_term} cannot receive mail as written, so failure reports are dropped.',
    fix: 'Correct the address in the ruf tag, or remove the tag.',
    rfc: 'RFC 9991 §2',
    vars: ['offending_term'],
  },

  // --- External destination verification (RFC 9990 §4 / RFC 9991 §5) --------
  {
    code: 'DMARC_EDV_MISSING',
    record: 'DMARC',
    severity: 'CRITICAL',
    category: 'reporting',
    title: 'External report destination has not authorised you',
    why: 'Reports for {domain} are addressed to {target}, a different domain. Receivers only send them if {target} publishes permission, and it does not, so those reports are being dropped by every receiver, silently.',
    fix: 'Ask {target} to publish a TXT record at {domain}._report._dmarc.{target} containing v=DMARC1',
    rfc: 'RFC 9990 §4',
    vars: ['domain', 'target'],
  },
  {
    code: 'DMARC_EDV_MALFORMED',
    record: 'DMARC',
    severity: 'CRITICAL',
    category: 'reporting',
    title: 'External authorisation record is invalid',
    why: 'The record at {domain}._report._dmarc.{target} exists but is not a valid authorisation, so receivers treat it as no permission at all and drop the reports.',
    fix: 'The record must contain v=DMARC1. Ask {target} to republish it in that exact form.',
    rfc: 'RFC 9990 §4',
    vars: ['domain', 'target'],
  },
  {
    code: 'DMARC_EDV_UNVERIFIED',
    record: 'DMARC',
    severity: 'LOW',
    category: 'reporting',
    title: 'External authorisation could not be checked',
    why: 'The authorisation lookup for {target} did not answer, so we cannot say whether your reports are being delivered there. This is usually a temporary DNS problem at {target}, not a fault in your record.',
    fix: 'Re-run the checkup shortly. If it keeps failing, ask {target} whether their nameservers are healthy.',
    rfc: 'RFC 9990 §4',
    dismissible: true,
    vars: ['target'],
  },
  {
    code: 'DMARC_EDV_MISSING_PARTIAL',
    record: 'DMARC',
    // Not critical: reports still arrive at the in-domain address, so the
    // owner is not blind. What they lose is the copy going to a third party.
    severity: 'MEDIUM',
    category: 'reporting',
    title: 'One reporting destination is not authorised to receive your reports',
    why: 'Reports addressed to {target} are dropped, because {target} has not published the record that authorises it to receive reports about {domain}. You still get reports at your own address, so you are not blind, but whoever expected a copy at {target} is getting nothing and probably does not know.',
    fix: 'Ask {target} to publish a TXT record at {domain}._report._dmarc.{target} containing v=DMARC1. If that address belongs to a vendor you no longer use, remove it from your rua tag instead.',
    rfc: 'RFC 9990 §4',
    vars: ['domain', 'target'],
  },
  {
    code: 'DMARC_EDV_MALFORMED_PARTIAL',
    record: 'DMARC',
    severity: 'MEDIUM',
    category: 'reporting',
    title: 'One reporting destination has a malformed authorisation record',
    why: 'The authorisation record at {domain}._report._dmarc.{target} exists but does not start with v=DMARC1, so receivers treat it as absent and drop reports addressed to {target}. Your own address still receives, so this costs you a copy rather than the whole picture.',
    fix: 'Ask {target} to republish that TXT record containing exactly v=DMARC1, with nothing before it.',
    rfc: 'RFC 9990 §4',
    vars: ['domain', 'target'],
  },
];
