import type { Issue } from '../types.js';

/**
 * Bloodwork — what a DMARC aggregate report says about a domain.
 *
 * These are the only findings in the catalog that come from a file rather than
 * from DNS, and they never touch Vitals: a report describes last week's mail,
 * not today's configuration, and mixing the two would let a quiet week flatter
 * a broken domain. They are read in the patient's browser and instantiated
 * there, which is why they also ship as their own entry point.
 */
export const RUA_ISSUES: readonly Issue[] = [
  {
    code: 'RUA_UNAUTHENTICATED_DELIVERED',
    record: 'RUA',
    severity: 'CRITICAL',
    category: 'alignment',
    title: 'Somebody is sending as you, and it is being delivered',
    why: '{count} messages ({share}% of everything in these reports) carried {domain} in the From address, failed DMARC outright, and were delivered anyway, across {sources} sending sources you have not authorised. Every one of those landed in an inbox wearing your name.',
    fix: 'Identify each source in the table below. Authorise the ones that are yours by adding them to SPF and signing them with DKIM; then move your policy to p=quarantine so the rest stop arriving.',
    rfc: 'RFC 9989 section 4.4',
    vars: ['count', 'share', 'sources', 'domain'],
  },
  {
    code: 'RUA_UNAUTHENTICATED_LEAKING',
    record: 'RUA',
    severity: 'HIGH',
    category: 'policy',
    title: 'Unauthenticated mail is getting past your policy',
    why: 'You publish p={policy}, but {count} failing messages from {sources} unauthorised sources were still delivered normally. Receivers apply your policy at their own discretion, and a partial rollout or a receiver-side exception let these through.',
    fix: 'Check the pct tag on your record, anything below 100 tells receivers to apply the policy to a sample only. Then look at the override reasons in the table, which name exactly why each receiver stood down.',
    rfc: 'RFC 9989 section 4.5',
    vars: ['count', 'sources', 'policy'],
  },
  {
    code: 'RUA_UNAUTHENTICATED_BLOCKED',
    record: 'RUA',
    severity: 'INFO',
    category: 'policy',
    title: 'Your policy stopped forged mail',
    why: '{count} messages from {sources} sources failed DMARC and were quarantined or rejected because you publish p={policy}. This is the treatment working exactly as prescribed.',
    fix: 'Nothing to change. Keep an eye on the blocked sources in case one of them turns out to be a service of your own that nobody told you about.',
    rfc: 'RFC 9990 section 3.1.1',
    vars: ['count', 'sources', 'policy'],
    dismissible: true,
  },
  {
    code: 'RUA_OWN_MAIL_FAILING',
    record: 'RUA',
    severity: 'HIGH',
    category: 'alignment',
    title: 'Your own mail is failing authentication',
    why: '{count} messages ({share}% of your volume) came from {sources} sources that identify themselves with your domain and still failed DMARC. That is a broken configuration, not an attacker, and the moment you enforce a policy, this is the mail you lose.',
    fix: 'For each source below: if it signs with DKIM, the selector or key is wrong, republish the key your platform gives you. If it only uses SPF, add its sending hosts to your SPF record. Fix these before tightening your policy.',
    rfc: 'RFC 9989 section 4.4',
    vars: ['count', 'share', 'sources'],
  },
  {
    code: 'RUA_READY_FOR_ENFORCEMENT',
    record: 'RUA',
    severity: 'INFO',
    category: 'policy',
    title: 'You are ready to turn enforcement on',
    why: '{rate}% of the mail in {days} days of reports authenticates and aligns, and none of the failures are yours. Staying at p=none now means collecting evidence you have already acted on while anyone can still send as {domain}.',
    fix: 'Move to p=quarantine with pct=25, watch a week of reports, then raise to pct=100 and finally to p=reject. Change one thing at a time so any surprise is easy to attribute.',
    rfc: 'RFC 9990 section 9.2',
    vars: ['rate', 'days', 'domain'],
  },
  {
    code: 'RUA_POLICY_NONE_UNPROTECTED',
    record: 'RUA',
    severity: 'HIGH',
    category: 'policy',
    title: 'Reports are arriving, but nothing is being stopped',
    why: 'You publish p=none, so receivers report on forged mail and deliver it anyway. {rate}% of this volume aligns and {count} messages did not, and not one of the failures was blocked, because you have not asked anyone to block them.',
    fix: 'Treat what the table shows: authorise your real senders, then move {domain} to p=quarantine. p=none is a diagnosis, not a treatment.',
    rfc: 'RFC 9989 section 4.5',
    vars: ['rate', 'count', 'domain'],
  },
  {
    code: 'RUA_READY_FOR_REJECT',
    record: 'RUA',
    severity: 'INFO',
    category: 'policy',
    title: 'Quarantine is doing its job, go to reject',
    why: '{rate}% of your mail aligns and nothing of yours is failing. Quarantine still delivers forged mail to a folder your recipients can open; reject refuses it at the door.',
    fix: 'Change p=quarantine to p=reject on _dmarc.{domain}. Keep your rua address so the reports keep coming.',
    rfc: 'RFC 9990 section 9.2',
    vars: ['rate', 'domain'],
  },
  {
    code: 'RUA_NOTHING_ALIGNED',
    record: 'RUA',
    severity: 'CRITICAL',
    category: 'alignment',
    title: 'Not one message in these reports authenticated',
    why: 'All {count} messages seen for {domain} failed both aligned SPF and aligned DKIM. Either your authentication is not published at all, or the domain in your From address does not match what your servers are signing and sending as.',
    fix: 'Run the full checkup on the domain first, this pattern almost always means a missing DKIM signature or an SPF record that covers the envelope domain rather than the one your recipients see.',
    rfc: 'RFC 9989 section 4.4',
    vars: ['count', 'domain'],
  },
  {
    code: 'RUA_SPF_ONLY_SOURCE',
    record: 'RUA',
    severity: 'MEDIUM',
    category: 'alignment',
    title: 'Some senders pass on SPF alone',
    why: '{sources} sources, carrying {count} messages, authenticate with SPF and publish no DKIM signature at all. SPF does not survive forwarding: the moment a recipient auto-forwards one of these, the envelope changes, SPF fails, and there is no signature left to save it.',
    fix: 'Turn DKIM signing on at each of those platforms and publish the selector they give you. DKIM travels with the message; SPF does not.',
    rfc: 'RFC 9989 section 4.4.2',
    vars: ['sources', 'count'],
  },
  {
    code: 'RUA_FORWARDED_MAIL',
    record: 'RUA',
    severity: 'INFO',
    category: 'reporting',
    title: 'Some of this is forwarded mail, not an attack',
    why: '{count} messages ({share}%) show the signature of relayed mail, a mailing list or an auto-forward that changed the envelope on the way. It is normal, it is not someone impersonating you, and it is the single most common reason a healthy domain sees failures.',
    fix: 'Leave it alone. Just make sure those messages are DKIM-signed, because a surviving signature is what keeps forwarded mail passing DMARC.',
    rfc: 'RFC 9990 section 3.1.6',
    vars: ['count', 'share'],
    dismissible: true,
  },
  {
    code: 'RUA_DKIM_BROKEN_IN_TRANSIT',
    record: 'RUA',
    severity: 'LOW',
    category: 'crypto',
    title: 'Your DKIM signatures are being broken on the way',
    why: '{sources} sources show a signature from your own domain that failed verification on relayed mail. Something between you and the recipient is editing messages, a mailing list footer, a subject-line tag, or a gateway rewriting the body, and that edit invalidates the signature.',
    fix: 'Sign with relaxed/relaxed canonicalisation so light reformatting survives, and keep signed header lists short. Mailing lists that rewrite the From address will always break DKIM, and ARC is the only real answer there.',
    rfc: 'RFC 9989 section 4.4.1',
    vars: ['sources'],
  },
  {
    code: 'RUA_PCT_PARTIAL',
    record: 'RUA',
    severity: 'MEDIUM',
    category: 'policy',
    title: 'Your policy only applies to part of your mail',
    why: 'The reports show pct={pct}, so receivers apply your policy to roughly {pct}% of failing messages and deliver the other {rest}% as if you had published nothing. Anyone sending as {domain} simply retries until they land in the untreated share.',
    fix: 'Once a week of reports looks clean, remove the pct tag entirely. It is a ramp for a rollout, not a setting to leave behind.',
    rfc: 'RFC 9989 section 4.7',
    vars: ['pct', 'rest', 'domain'],
  },
  {
    code: 'RUA_TESTING_MODE',
    record: 'RUA',
    severity: 'MEDIUM',
    category: 'policy',
    title: 'Your DMARC record is still marked as testing',
    why: 'The published policy carries t=y, which tells receivers you are experimenting and that they may treat {domain} more gently than your policy asks. Enforcement you have announced is not enforcement anyone is obliged to apply.',
    fix: 'Remove t=y from the record once you trust your reports. Leaving it in place is the quietest way to have a strict policy that does nothing.',
    rfc: 'RFC 9989 section 4.7',
    vars: ['domain'],
  },
  {
    code: 'RUA_SUBDOMAIN_POLICY_WEAKER',
    record: 'RUA',
    severity: 'MEDIUM',
    category: 'policy',
    title: 'Your subdomains are protected more weakly than your domain',
    why: 'You publish p={p} for {domain} but sp={sp} for everything beneath it. Attackers read DMARC records too, and invoices.{domain} is exactly as convincing to a recipient as the domain itself.',
    fix: 'Set sp to match p. If a subdomain genuinely needs a softer policy, publish a DMARC record on that subdomain rather than weakening every subdomain at once.',
    rfc: 'RFC 9989 section 4.7',
    vars: ['p', 'sp', 'domain'],
  },
  {
    code: 'RUA_POLICY_OVERRIDDEN',
    record: 'RUA',
    severity: 'LOW',
    category: 'reporting',
    title: 'Receivers overrode your policy',
    why: 'Receivers recorded {types} kinds of override on {count} messages, most often "{type}". An override means the receiver decided its own judgement beat your published policy, usually for forwarded or list mail it already trusts.',
    fix: 'Read the reason against each source in the table. These are informative, not errors: they explain why a message you expected to be blocked was delivered, or the reverse.',
    rfc: 'RFC 9990 section 3.1.6',
    vars: ['type', 'types', 'count'],
    dismissible: true,
  },
  {
    code: 'RUA_REPORTER_DISAGREES',
    record: 'RUA',
    severity: 'LOW',
    category: 'reporting',
    title: 'The reporter’s verdict does not match its own evidence',
    why: 'On {count} messages, the receiver recorded a DMARC result that the authentication details in the same report do not support, {reported}% pass by the reporter’s summary against {computed}% by the identifiers it actually listed. This is almost always relayed mail credited to the forwarder rather than to you.',
    fix: 'Trust the detail over the summary. Open those sources below and look at which domain each SPF or DKIM result belongs to, if it is not yours, that message did not pass DMARC for you.',
    rfc: 'RFC 9990 section 3.1.1',
    vars: ['count', 'reported', 'computed'],
    dismissible: true,
  },
  {
    code: 'RUA_SAMPLE_DATA',
    record: 'RUA',
    severity: 'INFO',
    category: 'operational',
    title: 'This report contains example addresses',
    why: '{sources} of the sending addresses sit in ranges reserved for documentation, which no real mail server may use. This file is a sample or a test fixture rather than a record of mail anyone actually sent.',
    fix: 'Read it to learn the shape of a report, then load the real ones your rua address is collecting.',
    rfc: 'RFC 9990 section 3.1.1',
    vars: ['sources'],
    dismissible: true,
  },
  {
    code: 'RUA_PRIVATE_SOURCE_IP',
    record: 'RUA',
    severity: 'LOW',
    category: 'operational',
    title: 'Mail is being reported from private addresses',
    why: '{sources} sources use addresses that cannot be routed on the internet, private, loopback or link-local ranges. Something inside a network is injecting mail and the reporting path is recording the internal hop instead of the public one.',
    fix: 'Find the relay behind those addresses. Its public sending IP is the one that has to be in your SPF record, and it is not in these reports.',
    rfc: 'RFC 9990 section 3.1.1',
    vars: ['sources'],
  },
  {
    code: 'RUA_LOW_VOLUME',
    record: 'RUA',
    severity: 'INFO',
    category: 'reporting',
    title: 'Not enough mail here to conclude much',
    why: 'These reports cover {count} messages. A percentage from a sample that size moves several points on a single delivery, so treat the sources below as real and the rates as provisional.',
    fix: 'Collect a fortnight of reports before making a policy change. Every large receiver sends one a day, so the picture fills in quickly.',
    rfc: 'RFC 9990 section 9.2',
    vars: ['count'],
    dismissible: true,
  },
  {
    code: 'RUA_SHORT_WINDOW',
    record: 'RUA',
    severity: 'INFO',
    category: 'reporting',
    title: 'This is a narrow window',
    why: 'You have loaded {reports} report(s) covering about {days} day(s). Monthly invoicing, campaigns and payroll all send from senders that will not appear in a window this short.',
    fix: 'Drop in every report you have. They merge into one picture, and a source that only sends once a month is exactly the one that breaks when you enforce.',
    rfc: 'RFC 9990 section 9.2',
    vars: ['reports', 'days'],
    dismissible: true,
  },
  {
    code: 'RUA_POLICY_CHANGED',
    record: 'RUA',
    severity: 'INFO',
    category: 'policy',
    title: 'Your policy changed during this window',
    why: 'The loaded reports describe {variants} different published policies, so part of this data was collected under rules you have since changed. Reports always describe the policy that was live when the mail was sent.',
    fix: 'Compare like with like: analyse the reports from before and after the change separately when judging whether the change worked.',
    rfc: 'RFC 9990 section 3.3',
    vars: ['variants'],
    dismissible: true,
  },
  {
    code: 'RUA_REPORTER_ERROR',
    record: 'RUA',
    severity: 'INFO',
    category: 'reporting',
    title: 'The reporter recorded a problem of its own',
    why: 'The receiver attached {count} error note(s) to this report. Usually it means it could not fully resolve your policy or your reporting address at the time, so the data may be incomplete.',
    fix: 'Read the note in the evidence below. If it mentions your reporting address, verify the external-destination authorisation record at your report host.',
    rfc: 'RFC 9990 section 3.1.5',
    vars: ['count'],
    dismissible: true,
  },
];
